services:
  # Web interface service
  - type: web
    name: clipboard-manager-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    plan: starter
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clipboard-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true

  # Background service for clipboard monitoring (optional)
  - type: worker
    name: clipboard-manager-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python clipboard_app.py --cli --monitor
    plan: starter
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clipboard-db
          property: connectionString

databases:
  # Postgres database for storing clipboard history
  - name: clipboard-db
    plan: starter
    ipAllowList: [] # only allow internal connections